---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: httpbin-local
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: httpbin-http
      protocol: HTTP
    hosts:
    - "local.httpbin.org"
